# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
    config: './rubocop.yml'

# add the files here you want to be ignored by stylelint
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "README.md"
    - "node_modules/**/*"
    - "spec/support/*"

# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

# find full documentation here: https://stickler-ci.com/docs